server.port=8084
spring.application.name=booking-service

# PostgreSQL Database Connection Configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/cineverse_booking
spring.datasource.username=postgres
spring.datasource.password=Pranjali@1607

# Hibernate Automated Table Definition Generator
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true