server.port=8084
spring.application.name=booking-service

# PostgreSQL Database Connection Configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/cineverse_booking
spring.datasource.username=postgres
spring.datasource.password=Pranjali@1607

# Hibernate Automated Table Definition Generator
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.redis.host=localhost
spring.redis.port=6379
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Enable listener retries
spring.rabbitmq.listener.simple.retry.enabled=true
# Try to process the message a maximum of 3 times
spring.rabbitmq.listener.simple.retry.max-attempts=3
# Wait 2 seconds before the first retry
spring.rabbitmq.listener.simple.retry.initial-interval=2000
# Do not re-queue failed messages back to the main queue; drop them to DLQ after exhausting retries
spring.rabbitmq.listener.simple.default-requeue-rejected=false